#!/usr/bin/env python

from sys import argv
from os import getcwd, execl

import re
import csv

def load_csv (path):
    reader = csv.reader (open (path, "r"))
    header = reader.next ()
    values = []
    for line in reader:
        item = {}
        for key, value in zip (header, line):
            item[key] = value
        values.append (item)
    return values


if __name__ == '__main__':
    path = getcwd () + '/' + argv[0]
    path_match = re.match ('^(.*/web2py/)applications/([^/]+)/.*', path)
    if not path_match:
        print "Error: Can't find web2py.py location. You need to have a standard web2py application directory structure for this script to work (or use the --web2py and --app options)"
        exit (1)
    web2py_path = path_match.group (1)
    app_name = path_match.group (2)
    exec_path = web2py_path + 'web2py.py'
    execl (exec_path, exec_path, '--shell=' + app_name, '--run=' + path, '--import_models' , '-A', argv[1])

data = load_csv (argv[1])
    
